### ISSUE TITLE
Movement Not working for me

### ISSUE THREAD

**Issue by KamKamee** [chriscourses/pokemon-style-game#3]
Im new to game/website development and I wanted to recreate this game and modify it for my school subject but as i was gonna test the game out using my browser it wont work for me....

I inpect the website and i get spammed with these errors

"classes.js:60 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at Sprite.draw (http://127.0.0.1:5500/classes.js:60:7)
    at http://127.0.0.1:5500/index.js:209:16
    at Array.forEach (<anonymous>)
    at animate (http://127.0.0.1:5500/index.js:208:15)"

**Comment by mylchenko-alexander** [comment]
And what the Image state? Image url is exists? This error about your image (path)!

**Comment by KamKamee** [comment]
@MylchenkoAlexandr oh I dont know yet where can I exactly see if the image path is correct or not may you please help me?

**Comment by mylchenko-alexander** [comment]
I try to run - movement work correctly! Use the WASD keyboard keys ;)
I just run index.html and all still work, without any exceptions.

**Comment by KamKamee** [comment]
@MylchenkoAlexandr Is that so... I tried recreating the project using the raw codes and run it on WASD but it seems that I am still having trouble with the movements... I guess its just for me huh

but anyways ty anyways for helping me ill try to research more on my problem
